[project]
name = "chat-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "gel>=3.1.0",
    "pydantic-ai>=0.2.10",
]
